accounts/urls.py
from django.urls import path
from . import views

app_name = 'accounts'

urlpatterns = [
    path('register/', views.register, name='register'),
    path('login/', views.login, name='login'),
    path('logout/', views.logout, name='logout'),
    path('activate/<uidb64>/<token>/', views.activate, name='activate'),

    path('', views.dashboard, name='dashboardd'),
    path('dashboard/', views.dashboard, name='dashboard'),
    path('my_orders/', views.my_orders, name='my_orders'),
    path('edit_profile/', views.edit_profile, name='edit_profile'),
    path('change_password/', views.change_password, name='change_password'),
    path('order_detail/<int:order_id>/', views.order_detail, name='order_detail'),
    
    path('forget_password/', views.forget_password, name="forget_password"),
    path('resetpassword_validate/<uidb64>/<token>/', views.resetpassword_validate, name='resetpassword_validate'),
    path('reset_password/', views.reset_password, name="reset_password"),
]

cart/urls.py
from django.urls import path
from . import views 

app_name = 'cart'

urlpatterns = [
    path('', views.cart, name='cart'),
    path('add_cart/<int:product_id>/', views.add_cart, name='add_cart'),
    path('remove_cart/<int:product_id>/<int:cart_item_id>/', views.remove_cart, name='remove_cart'),
    path('remove_cart_item/<int:product_id>/<int:cart_item_id>/', views.remove_cart_item, name='remove_cart_item'),
    
    
]

core/urls.py
from django.contrib import admin
from django.urls import path
from django.urls.conf import include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('shop.urls', namespace='shop')),
    path('account/', include('accounts.urls', namespace='accounts')),
    path('cart/', include('cart.urls', namespace='cart')),
    path('orders/', include('orders.urls', namespace='orders')),
]+ static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/includes/alerts.html
{% if messages %}

    {% for message in messages %}
    <div id="message" class="container text-center">
    <div {% if message.tags %} class="alert alert-{{ message.tags }}"{% endif %} role="alert">
    <button type="button" class="close" data-dismiss="alert"><span aria-hidden="true">&times;</span></button>
        {% if message.level == DEFAULT_MESSAGE_LEVELS.ERROR %}{% endif %}
        {{ message }}
    </div>
    </div>
    {% endfor %}

{% endif %}

templates/includes/dashboard_slider.html
<!--<aside class="col-md-3">-->
<aside class="col-md-3">
	<!--   SIDEBAR   -->
	<ul style="font-size:16px;" class="list-group">
		<a class="list-group-item {% if '/dashboard/' in request.path  %}active{% endif %}" href="{% url 'accounts:dashboard' %}"> Dashboard </a>
		<a class="list-group-item {% if '/my_orders/' in request.path %}active{% endif %}" href="{% url 'accounts:my_orders' %}"> My Orders </a>
		<a class="list-group-item {% if '/edit_profile/' in request.path  %}active{% endif %}" href="{% url 'accounts:edit_profile' %}">Profile</a>
		<a class="list-group-item {% if '/change_password/' in request.path  %}active{% endif %}" href="{% url 'accounts:change_password' %}">Change Password</a>
		<a style="color:#21094E;" class="list-group-item" href="{% url 'accounts:logout' %}"><b>Log out</b> 	&nbsp;  <i class="fa fa-power-off"></i> <span class="text"></a>
	</ul>
	
	
</aside>